# image.nvim
set -gq allow-passthrough on

# Faster movement
set -sg escape-time 0

# True colors
set-option -sa terminal-overrides ",xterm*:Tc"

# mouse support
set -g mouse on

# Start windows and panes at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-strategy-nvim 'session'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'niksingh710/minimal-tmux-status'

set -g @minimal-tmux-bg "#FA8D3F"

set -g @sessionx-bind 'o'

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle

# In copy mode (vi), make 'y' copy selection without exiting copy mode
bind-key -T copy-mode-vi y send -X copy-pipe 'xclip -in -selection clipboard'

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind-key -n S-Left swap-window -d -t -1
bind-key -n S-Right swap-window -d -t +1
bind-key -n M-h previous-window
bind-key -n M-l next-window

set -g status-interval 1


# setw -g automatic-rename-format '#I:#(bash -c "p=#{pane_current_path}; echo \\$(basename \\$(dirname \\"\\$p\\"))/\\$(basename \\"\\$p\\")")'
# setw -g automatic-rename on

bind-key b set-option status

run '~/.tmux/plugins/tpm/tpm'
