[settings]
screenchange-reload = true
pseudo-transparency = true

[global/wm]
margin-top = 0
margin-bottom = 0

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
;   Bar Templates
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[bar/base]
width = 100%
height = 28
offset-x = 0
offset-y = 0
fixed-center = true

background = #FFFFFF
foreground = #000000

line-size = 2
line-color = #FA8D3E

border-size = 0
padding-left = 2
padding-right = 2
module-margin = 1

font-0 = "Hack Nerd Font:size=10;2"
font-1 = "Hack Nerd Font:size=12;3"

modules-left = i3
modules-center = date
modules-right = wireless-network ethernet memory cpu volume battery

cursor-click = pointer
cursor-scroll = ns-resize

tray-padding = 2
tray-background = #FFFFFF


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
;   Specific Bar Definitions
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[bar/film]
inherit = bar/base
monitor = FILM
tray-position = right

[bar/work-left]
inherit = bar/base
monitor = DP-4
tray-position = none

[bar/work-center]
inherit = bar/base
monitor = DP-0
tray-position = right ; Tray on primary monitor

[bar/work-right]
inherit = bar/base
monitor = DP-2
tray-position = none


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
;   Module Definitions
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/i3]
type = internal/i3
pin-workspaces = true
strip-wsnumbers = true
index-sort = true
enable-click = true
enable-scroll = true
wrapping-scroll = false
ws-icon-default = 
format = <label-state> <label-mode>
label-mode = %mode%
label-mode-padding = 2
label-mode-background = #FA8D3E
label-mode-foreground = #FFFFFF
label-focused = %index%
label-focused-background = #FA8D3E
label-focused-underline= #FA8D3E
label-focused-padding = 2
label-focused-foreground = #FFFFFF
label-unfocused = %index%
label-unfocused-padding = 2
label-unfocused-foreground = #000000
label-visible = %index%
label-visible-background = #C8C8C8
label-visible-underline = #C8C8C8
label-visible-padding = 2
label-visible-foreground = #000000
label-urgent = %index%
label-urgent-background = #FF0000
label-urgent-padding = 2
label-urgent-foreground = #FFFFFF

[module/date]
type = internal/date
interval = 1
date = " %A %e.%B"
time = " %H:%M:%S"
format-underline = #FA8D3E
label = %date% %time%

[module/wireless-network]
type = internal/network
interface = wlan0
interval = 3.0
format-connected = <ramp-signal> <label-connected>
format-connected-underline = #FA8D3E
label-connected = %essid%
format-disconnected = <label-disconnected>
label-disconnected =  down
label-disconnected-foreground = #666666
ramp-signal-0 = 
ramp-signal-1 = 
ramp-signal-2 = 
ramp-signal-3 = 
ramp-signal-4 = 
ramp-signal-foreground = #000000

[module/ethernet]
type = internal/network
interface = eth0
interval = 3.0
format-connected = 󰈀 <label-connected>
format-connected-underline = #FA8D3E
label-connected = %linkspeed%
format-disconnected = <label-disconnected>
label-disconnected = 󰈀 down
label-disconnected-foreground = #666666

[module/memory]
type = internal/memory
interval = 2
format-prefix = "󰍛 "
format-prefix-foreground = #FA8D3E
format-underline = #FA8D3E
label = %percentage_used%%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " "
format-prefix-foreground = #FA8D3E
format-underline = #FA8D3E
label = %percentage:2%%

[module/volume]
type = internal/pulseaudio
use-ui-max = false
interval = 5
format-volume = <ramp-volume> <label-volume>
format-volume-underline = #FA8D3E
label-volume = %percentage%%
label-volume-foreground = #000000
format-muted-prefix = " "
format-muted-foreground = #666666
label-muted = muted
ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-volume-foreground = #000000

[module/battery]
type = internal/battery
battery = BAT0
adapter = AC
full-at = 98
poll-interval = 5
format-charging = <animation-charging> <label-charging>
format-charging-underline = #FA8D3E
format-discharging = <ramp-capacity> <label-discharging>
format-discharging-underline = #FA8D3E
format-full-prefix = " "
format-full-underline = #FA8D3E
label-charging = %percentage%%
label-discharging = %percentage%%
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-foreground = #000000
animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-framerate = 750
